### ISSUE TITLE
placeholder is not defined on Checkboxes

### ISSUE THREAD

**Issue by swarakaka** [tanthammar/tall-forms#104]
`Call to undefined method Tanthammar\TallForms\Checkboxes::placeholder()`

**Comment by swarakaka** [comment]
it may have been misspelled in documentations with placeholders , otherwise the checkbox should originally have a label.

`protected function fields()
{
    return [

        filled($this->events) ? Checkboxes::make('Attach to Events', 'event_ids')
            ->options($this->events)
            ->relation()
            ->placeholder(trans('global.select').' '.trans('crud.event.title_singular'))
            ->rules('nullable|array|exists:events,id') : null,
    ];
}`

**Comment by tanthammar** [comment]
Checkboxes doesn't have a `placeholder()` method.

The `->options(...)` becomes each `Checkbox` label.
The `::make()` method sets the `Checkboxes` label.

Based on your code I would suggest the following
```php
Checkboxes::make(trans('global.select').' '.trans('crud.event.title_singular'), 'event_ids')
        ->options($this->events)
        ->relation()
        ->rules('nullable|array|exists:events,id')
```
