### ISSUE TITLE
how to store data in a json column?

### ISSUE THREAD

**Issue by Codemainmx** [tanthammar/tall-forms#106]
hello! I have a column in my database called values of type json
in the model I have the casts, but it does not save my data
![image](https://user-images.githubusercontent.com/96995770/152231824-d368145c-98b7-49bd-89ce-84930979d8a8.png)

in my fields I have this ...
when I save data all the fields are saved except values
do I need something else?
Thanks in advance!
![image](https://user-images.githubusercontent.com/96995770/152231963-8ec2a8ae-b195-4d68-8c1d-f9e641731f37.png)

**Comment by tanthammar** [comment]
You have not added `values` to the models `$fillable` array
