### ISSUE TITLE
"views/components/pages/default.blade.php"  not created

### ISSUE THREAD

**Issue by devel-23** [tanthammar/tall-forms#112]
hi,

in the [installation docs](https://tina-hammar.gitbook.io/tall-forms/installation/quickstart-artisan-cmd#summary) its says that the `views/components/pages/default.blade.php` is altered ( = created?) but it seems that it never gets created leading to the errors as outlined in the [manual install ](https://tina-hammar.gitbook.io/tall-forms/installation/manual-installation/wrapper-view) related to the missing wrapper view. 
shouldn't the default wrapper view be installed in the artisan command?

**Comment by tanthammar** [comment]
Yes it should. I'll check.

**Comment by tanthammar** [comment]
@devel-23 
The installer creates 'views/layouts/tall-form-wrapper-layout.blade.php', and sets the config to 'layouts.tall-form-wrapper-layout'. I will update the documentation. Thank you.
