### ISSUE TITLE
Edit method

### ISSUE THREAD

**Issue by jouniikaheimo** [tanthammar/tall-forms#12]
How i can create edit button, every documents only how create form..

yes i know @livewire('edit-form', ['model' => $model]) but if i same pages multiple entry how i can add edit button and click edit only specified entry

**Comment by tanthammar** [comment]
Let's say you have a view table showing all Users. 
You have to add a route link to each row that passes the model. 
Just like a normal Laravel project.

Example: (Using my favourite Route::livewire)

web.php
```php
Route::livewire("/users/edit/{user}", "your-form-path.the-name-of-your-form-component")->name("users.edit");
```

In the table with all users, on each user row
```blade
<a href="{{ route('users.edit', ['user' => $user->id]) }}">Edit User</a>
```

Create your tall-forms component using the `--action=update` option in the `make:tall-form` command. 
Then you will get a form with all the parameters you need.

The mount() method based on this example
```php
    public function mount(User $user)
    {
        $this->fill([
            'formTitle' => 'Update User',
            'action' => 'update',
            'spaMode' => true, //if you used Route::livewire like this example
            'showGoBack' => false, //or true
        ]);

        $this->mount_form($user);
    }
```

**Comment by tanthammar** [comment]
Or, if you do not want to use `Route::livewire`

Then you do it **exactly like in a standard Laravel project** with a `get` route, and a view that you pass the model.
And a link like in my example above.
In the view you embed the livewire component as described in the Livewire docs.

//for the user example update form
```blade
@livewire('the-name-and-path-to-your-form', ['user' => $user])
//or
<livewire:'the-name-and-path-to-your-form', :user=$user />
```

Or, you can have a single form in some kind of modal, that you pass the model id via browser event, and setup a listener in the form component that loads the model on the event. (In this case you should not pass the model to the mount method)
[Read about listeners in Livewire docs](https://laravel-livewire.com/docs/events)

**Comment by tanthammar** [comment]
@jouniikaheimo can I close this issue?

**Comment by jouniikaheimo** [comment]
ahh sorry slow answer ... your answer works fine i close this..
