### ISSUE TITLE
Missing clear example in Documentation

### ISSUE THREAD

**Issue by christoferd** [tanthammar/tall-forms#121]
Problem is that I installed Tall-Forms and now I don't know how to use it. 
Documentation doesn't seem to show any examples on how to get started :-(

**Describe the solution you'd like**
Just like most other documentations, a Getting Started section.
Or, "How to Generate a Form"

"Create Forms" ... in that section I'd expect there to be a way to create a form in my app, actually get something going.

**Describe alternatives you've considered**
I've looked through the documentation. Cannot see clear examples for someone who is new to this package.

**Additional context**
Sorry, I must be missing something as I probably misunderstood the package.
"Laravel Livewire (TALL-stack) form generator with realtime validation, file uploads, array fields, blade form input components and more."
After reading this, I was eager to be able to generate a form, with realtime validation. But, cannot figure it out from documenation.

**Comment by tanthammar** [comment]
I assume you have a good understanding of how a Livewire component works.
Then the documentation covers most topics like validation, model binding etc.
I recommend you to read the "Create Forms" section, especially Create Forms->form types->standard form, which explains how to generate a general form for a Model.
Then you have the "Concepts" section and at the bottom of the menu you'll find examples for most field types.
