### ISSUE TITLE
ABORTING: This installer only supports Laravel >= v8

### ISSUE THREAD

**Issue by rabol** [tanthammar/tall-forms#124]
**Describe the bug**

Followed the installation from here:
https://tina-hammar.gitbook.io/tall-forms/installation/quickstart-artisan-cmd

and got the error:
ABORTING: This installer only supports Laravel >= v8

**Screenshots**

**Environment:**
 - Tall-forms version: Latest
 - Livewire version: latest
 - Laravel version:latest
 - AlpineJS version (only needed if problem is Alpine related):
 - $wrapWithLayout true/false:
    - if true, Are you using your own wrapper component or the default one?:
 - Optional model binding?
 - Have you published the view files?:
 - Have you published, and edited the config file?:
 - Is it a Create or Update form?:

**Fields Definition**
Please paste the code for your fields that is related to this issue.

**Comment by tanthammar** [comment]
I haven't tested the installer later than Laravel 9. Please follow the manual installation process.

**Comment by tanthammar** [comment]
Please use [Filament](https://filamentphp.com/) instead. I have decided to deprecate this package. Filament is a much better alternative and I've decided to shift my focus entirely to contributing to that package instead.
