### ISSUE TITLE
Version for new Livewire

### ISSUE THREAD

**Issue by arth2o** [tanthammar/tall-forms#125]
**Is your feature request related to a problem? Please describe.**
I've an issue with the installation. 
![form-generator-issue-to-install](https://github.com/tanthammar/tall-forms/assets/6150878/00490c71-d0f3-4281-afba-4009eedfe57a)

**Comment by tanthammar** [comment]
You're on Livewire 3. This package does not support that.

**Comment by hamrak** [comment]
It's possible to do that quickly (add support for Livewire 3) in new major version? :)

`php artisan livewire:upgrade`

https://livewire.laravel.com/docs/upgrading

**Comment by tanthammar** [comment]
That is an option.
I would accept a PR if you are willing to try that out.
Another option is Filament which has Livewire 3 support.

**Comment by tanthammar** [comment]
Please use [Filament](https://filamentphp.com/) instead. I have decided to deprecate this package. Filament is a much better alternative and I've decided to shift my focus entirely to contributing to that package instead.
