### ISSUE TITLE
Require php ^7.4.4 -> your php version (8.2.12) does not satisfy that requirement.

### ISSUE THREAD

**Issue by sachinmanath** [tanthammar/tall-forms#127]
**Describe the bug**
Not able to install and getting error "tanthammar/tall-forms[0.9, ..., 0.95, 1.0, ..., 1.01, 2.0, ..., 2.4.5, 3.0.0, ..., 3.1.0, 4.0.4, ..., 4.5.1] require php ^7.4.4 -> your php version (8.2.3) does not satisfy that requirement."

**Screenshots**
<img width="964" alt="Screenshot 2023-11-27 at 3 34 16 PM" src="https://github.com/tanthammar/tall-forms/assets/13333486/f1d2a6f8-9754-47fa-89ce-070978a63d4c">

**Environment:**
 - PHP(8.2.3)
 - Tall-forms version: 2.1
 - Livewire version: 3.1 
 - Laravel version: 10.10
 - AlpineJS version (only needed if problem is Alpine related):
 - $wrapWithLayout true/false:
    - if true, Are you using your own wrapper component or the default one?:
 - Optional model binding?
 - Have you published the view files?: No
 - Have you published, and edited the config file?: No
 - Is it a Create or Update form?:No

**Fields Definition**
Please paste the code for your fields that is related to this issue. - Installation Issue

**Comment by tanthammar** [comment]
This package does not support livewire 3. Suggest you to use Filament instead :)
