### ISSUE TITLE
Validation message are not user friendly. 

### ISSUE THREAD

**Issue by fawzanm** [tanthammar/tall-forms#13]
**Is your feature request related to a problem? Please describe.**
I think it would be better to have validation error messages if it doesn't show the `form data.`. 

<img width="515" alt="Screenshot 2020-08-18 at 09 11 30" src="https://user-images.githubusercontent.com/2080551/90473051-ff88ef00-e132-11ea-870f-9b7a2bfa81a9.png">

**Describe the solution you'd like**
It'd be friendlier if we show `The name fields is required` by stripping off the `form data.` part. 

If you are Okay with this I can send a PR.

**Comment by tanthammar** [comment]
I understand.

My projects are multi lingual, always have to [customize the validation attributes ->](https://laravel.com/docs/7.x/validation#customizing-the-validation-attributes) anyway, so for me this is not an issue.

But please make a PR! It is an improvement.

In the meanwhile you can use the [errorMsg()](https://github.com/tanthammar/tall-forms/wiki/Field-Options#errormsgstring-message) field method to display a custom message.

**Comment by tanthammar** [comment]
If you make a PR, please consider the array fields. 

A validation attribute for an array field, could look like this `form_data.program.0.label`.

**Comment by tanthammar** [comment]
@fawzanm I fixed this in v3.0.0 attribute validation works as default Laravel app, no "form data" is prefixing the fields
