### ISSUE TITLE
Problem with array field when using input fields

### ISSUE THREAD

**Issue by danielbehrendt** [tanthammar/tall-forms#14]
The following array field definition:

```
Field::make('Owners')->array([
    Field::make('First name')->input()->placeholder('First name')->rules('required'),
    Field::make('Last name')->input()->placeholder('Last name')->rules('required'),
]),
```
produces an exception when trying to add a new row

```
Undefined property: Tanthammar\TallForms\Field::$show_label 
(View: /vendor/tanthammar/tall-forms/resources/views/array-fields/input.blade.php)
```

**Comment by tanthammar** [comment]
You cannot declare `Field` inside a `Field`.
Only `ArrayField` or `KeyValField` 

-[Array docs](https://github.com/tanthammar/tall-forms/wiki/Array)
-[KeyVal docs](https://github.com/tanthammar/tall-forms/wiki/KeyVal)

**Comment by danielbehrendt** [comment]
Sorry, my fault :/
