### ISSUE TITLE
File input styling missing

### ISSUE THREAD

**Issue by danielbehrendt** [tanthammar/tall-forms#15]
It seems like the file input field is not completely styled and some undefined variables are used. Isn't the field ready to use?

**Comment by tanthammar** [comment]
To be honest, that field is inherited from the kdion pkg. I am refactoring it to use Livewire native file upload. 

So I have not given it any "love" yet...

Will release the new file upload field this week, if you can hold off those fields until then?

**Comment by danielbehrendt** [comment]
Awesome, of course I will hold off until then!

**Comment by tanthammar** [comment]
@danielbehrendt 
I made a new release where I added support for Livewire native file uploads.
Docs are in progress.
[Simple Instructions ->](https://github.com/tanthammar/tall-forms/wiki/File-uploads)

**Comment by danielbehrendt** [comment]
@tanthammar Thank the fix but the old field implementation throws an error and "Simple Instructions" link doesn't work. Do you have an quick advice how to fix the `Undefined variable` exception?

**Comment by tanthammar** [comment]
Does the link work now? maybe the wiki wasn't updated yet.
+ you must upgrade to v3.0.0, packagist isn't always very fast on registering new releases.

**Comment by tanthammar** [comment]
@danielbehrendt ping? Did you read the docs, how is it going?

**Comment by danielbehrendt** [comment]
@tanthammar yeah, today I've fiddled around to get it working together with the [Spatie Medialibrary](https://github.com/spatie/laravel-medialibrary) and now I'm trying to build to UI for handling existing files. 

Thanks for updating this package!

**Comment by tanthammar** [comment]
If you are using the Spatie Mlib you might want to wait for the next field I'm building. Se the end of the File upload docs. Will probably be done in a few days. I'm building it for myself wit the same purpose. @danielbehrendt

**Comment by tanthammar** [comment]
@danielbehrendt that field will handle existing images as well

**Comment by danielbehrendt** [comment]
@tanthammar I'm really excited

**Comment by tanthammar** [comment]
@danielbehrendt 

Just want to let you know that I will finish the image cropper field before I close this version and start refactoring for Livewire v2. (Don't know if you read the update on the Wikis home page)

**Comment by danielbehrendt** [comment]
@tanthammar how is it going with the Livewire v2 refactoring? Do you have any ETA?

**Comment by tanthammar** [comment]
I planned yesterday, but there are some Livewire bugs I waited for, that I'm currently making workarounds to be able to release anyway. Probably done today, but writing docs tomorrow. 

So. Tomorrow or the day after there'll be an rc you can test.

**Comment by tanthammar** [comment]
@danielbehrendt I completed the upgrade today.
Did not have the time do write new documentation. Will do that tomorrow. :)

**Comment by danielbehrendt** [comment]
@tanthammar I'm really excited to test the upgrade.

**Comment by danielbehrendt** [comment]
@tanthammar is it ready for testing? Can't install it via Composer or am I missing something?

**Comment by tanthammar** [comment]
@danielbehrendt do you get an error while installing?

**Comment by tanthammar** [comment]
@danielbehrendt please try again, I had a comment in composer.json, which I removed.

**Comment by tanthammar** [comment]
@danielbehrendt also, please read new docs (not ready with all of them) but start with https://github.com/tanthammar/tall-forms/wiki/v4-upgrade-guide

**Comment by tanthammar** [comment]
@danielbehrendt I've completed the documentation. A good start, to get an overview of new syntax, is to check out the [Example Form](../wiki/Example-form). It's using the same example as in v3.

**Comment by danielbehrendt** [comment]
@tanthammar Installation works now. Thanks for fixing that. Now I have to do sone migrations. Fortunately it's only 3 forms.

**Comment by tanthammar** [comment]
@danielbehrendt Glad to hear it's only a few forms. I was worried when rewriting everything but I believe it'll be better in the long run. 

Do you agree?

If you read the Custom Field doc you might see the benefits. :)

**Comment by tanthammar** [comment]
@danielbehrendt I just released the image cropper field.
