### ISSUE TITLE
What is the best way to add a component with "auto suggest"? 

### ISSUE THREAD

**Issue by elfeffe** [tanthammar/tall-forms#18]
Thank you for your package.
I just want to know what's the best way to add a component with auto suggest, a drop down that return results as you type.

Do I have to follow this? https://github.com/tanthammar/tall-forms/wiki/Livewire-child-component

I need to use the array of inputs, but I need to type the item name and get a list of the items that match that name, and then select with a click.

Is there any component that offers that?

**Comment by tanthammar** [comment]
In the current version v3.x.x, you would have to create a custom field or the Livewire-child-component.
In the new version v4 which will be released this week, it will be much easier.
I'll make a note, to create a tutorial in the wiki on how to achieve what you want, after v4 is released.
I see the need for such a component and I will consider creating one, but I have to release v4 first :)

**Comment by elfeffe** [comment]
Ok, if possible create a tutorial about how to create new components, so we can share ours

**Comment by tanthammar** [comment]
@elfeffe I released the new version of this package where I created a tutorial on how to contribute with custom fields. 
https://github.com/tanthammar/tall-forms/wiki/Custom-Field

(please read the upgrade guide first)

**Comment by elfeffe** [comment]
@tanthammar you did an amazing job, thank you for sharing

**Comment by tanthammar** [comment]
@elfeffe, just a short note, to tell you that I'll work on a search input field during next week.

**Comment by tanthammar** [comment]
Quick update. I'm done with this field but unable to release because there is an Alpine entangle issue. Waiting for the issue to be resolved.

**Comment by tanthammar** [comment]
https://github.com/livewire/livewire/issues/1782

**Comment by tanthammar** [comment]
@elfeffe The search field is released in v5. Please read the release notes. Will write documentation tomorrow.
