### ISSUE TITLE
Fix for laravel 8

### ISSUE THREAD

**Issue by shoemoney** [tanthammar/tall-forms#19]
Hello with laravel 8 it just uses a css and not sass so thought some others might find this handy.

here is my app.css after about 3 hours of playing between webpack and tailwind 

@import "tailwindcss/base";

@import url('https://fonts.googleapis.com/css2?family=Hind:wght@400;500;600;700&family=Mulish:wght@400;500;600;700;800;900&display=swap');

@import "tomorrow-night.css";

@import "tailwindcss/components";
@import "@fortawesome/fontawesome-svg-core";
@import "animations.css";
@import "code.css";
@import "toc.css";

@import "tailwindcss/utilities";
pre code.hljs {
  @apply p-5;
}
 module.exports =
{
theme: {

extend: {

fontFamily: {
  sans: [ 'Inter var', . . . defaultTheme . fontFamily . sans ],
}

colors: {

night: {
  darkest: '#2E3440';
  dark: '#3B4252';
  light: '#434C5E';
  lighter: '#4C566A';
}

,
snow: {
  dark: '#D8DEE9';
  medium: '#E5E9F0';
  light: '#ECEFF4';
}

,
frost: {
  green: '#8FBCBB';
  mint: '#88C0D0';
  dimmed: '#81A1C1';
  blue: '#5E81AC';
}

,
aurora: {
  red: '#BF616A';
  orange: '#D08770';
  yellow: '#EBCB8B';
  green: '#A3BE8C';
  pink: '#B48EAD'
}

}
}
}
}

**Comment by shoemoney** [comment]
Oups nevermined it bombed as yours requires v1 of tailwind.    Dang I am going out of town for a month and dying to try it!!

**Comment by tanthammar** [comment]
@shoemoney 

Thank you for sharing your efforts, I have not tested with Laravel 8 yet.

TailwindUI required Tailwind CSS >= v1.8, as this package is primary intended for TailwindUI I cannot do anything about that. 

Which version are you on? Can I change anything for you?


I would recommend you holding off installation of this package for a few days, because v4 will be a total rewrite, will save you a lot of refactoring.

**Comment by shoemoney** [comment]
Hey there.   I am in Jamaica for a week but I cloned it and upped the requirements and got it to install and hacked away.    Wouldn't recommend others do that but I wanted to see how cool the project is.     Really awesome and looking forward to it!

**Comment by elfeffe** [comment]
@tanthammar Any idea about when will the next version ready? Just to have an idea

**Comment by goldienz** [comment]
Also very keen to see a Laravel 8 compatible release of this. Can't wait!

**Comment by tanthammar** [comment]
Hi all, I have tested with Laravel 8 Jetstream installation today. 
Found no issues, so you should be good to go.
Please read the installation instructions, pay special attention to the new docs on the Tailwind config page.

@shoemoney, @goldienz , can I close this issue?

**Comment by goldienz** [comment]
> Hi all, I have tested with Laravel 8 Jetstream installation today.
> Found no issues, so you should be good to go.
> Please read the installation instructions, pay special attention to the new docs on the Tailwind config page.
> 
> @shoemoney, @goldienz , can I close this issue?

I will do some testing today and come back, but thank you so much for your work here!

**Comment by shoemoney** [comment]
I just got back from vacation and will test tonight/tomorrow with my current and a fresh install to confirm compatibility with laravel 8.  @tanthammar thank you so much for all of your work!

I am closing this as its related to the old version and if I find any bugs or issues will open a new one with specific details to that issue.
