### ISSUE TITLE
issue with saveFoo 

### ISSUE THREAD

**Issue by goldienz** [tanthammar/tall-forms#21]
I have a couple of forms which are using the saveFoo method, one being a file uploader, and one uses checkboxes.
Followed your examples (very handy i must add) and it all appeared to work fine, except it wouldnt save to the db table.

On the file upload, i tried with updatedFoo method, and the file would be uploaded and stored, but the value wouldnt be saved to the db table.

On the checkboxes, despite multiple boxes being checked, a dump of the $validated_value returns null.

I will freely admit, i've just started paying with this, and this could be a 'user error' and not necessarily a bug, but after seeing it on two separate things, i wondered if it may be related.

**Environment:**
 - Tall-forms version: 4.1.2
 - Livewire version: 1.2
 - Laravel: 8.6
 - Is it a Create or Update form?: Update
 - Have you installed and configured the laravel-blade-icons package?: Yes

**Fields Definition**
Component example (checkboxes) 
<code>
namespace App\Http\Livewire\Forms;

use Livewire\Component;
use Tanthammar\TallForms\Input;
use Tanthammar\TallForms\TallForm;
use Tanthammar\TallForms\Checkboxes;

use App\Models\Source;
use App\Models\Gateway;
use App\Models\Channel;

class GatewayChannelsUpdateForm extends Component
{
    use TallForm;

    public $channels;

    public function mount(Gateway $gateway)
    {
        //Gate::authorize()
        $this->fill([

            'wrapWithView' => false, //see https://github.com/tanthammar/tall-forms/wiki/installation/Wrapper-Layout
            'showGoBack' => false,
            'showReset' => false,
            'showDelete' => false,
            'inline' => false,
            'showTitle' => false,
        ]);

        $this->mount_form($gateway); // $gateway from hereon, called $this->model
    }

    // Optional method, this already exists in the TallForm trait
    public function onUpdateModel($validated_data)
    {
        $this->model = $this->model->update($validated_data);
    }

    public function beforeFormProperties()
    {
        // get existing relations, read the checkboxes docs about integer values
        $this->model->channel_ids = array_map('strval', optional($this->model->channels)->pluck('id')->all());

        // set the checkboxes options
        $this->channels = Channel::orderBy('name')->get()->pluck('id', 'name')->all();
    }

    public function fields()
    {

        return [
            Checkboxes::make('Select gateway channels', 'channel_ids')
                ->options($this->channels)
                ->relation()
                ->rules('nullable|array|exists:channels,id')
                ->wire('wire:model.defer')
        ];

    }

    public function saveChannelIds($validated_value)
    {
        //get the options that the user selected via the field name
        $selected_channels = $validated_value;

        //if the user unselected all available options it means we have to detach any existing relations
        dd($selected_channels);
        if (blank($selected_channels)) {
            $this->model->channels()->detach(); //detach all existing relations
        } else {
            //in this example we scoped the events to the users current team, so we check which events the user is allowed to attach
            //this is also a good example on how to validate the submitted data
            $allowed_to_sync = filled($selected_channels) ? array_intersect($selected_channels, array_values($this->channels)) : [];
            if (filled($allowed_to_sync)) $this->model->channels()->sync($selected_channels);
        }
    }
}
</code>

**Comment by goldienz** [comment]
Apologies for the horrific markdown!

**Comment by tanthammar** [comment]
I am not är the office right now. A small note from my phone:
Try $selected_channels = data_get($this->relationship_data, 'channel_ids');
dd($selected_channels);

Works?

Don't remember, on the fly, if it's relationhip_data or relationships_data. 

Please try both and let me know :)

(Very hard to reply w the phone keyboard)

**Comment by tanthammar** [comment]
Back at the office again.
The relation() save method worked differently in v3... disregard my previous comment about $relationship_data.
I released a fix 4.1.3.

Upgrade and this should work as documented:
```php

public function saveChannelIds($validated_value)
{
    //get the options that the user selected via the field name
    $selected_channels = $validated_value;
    dd($selected_channels);
}
```
Please let me know if there are any other errors, or please close this issue :).

Thank you for reporting.
//Tina

**Comment by goldienz** [comment]
Thanks for the fix, however the `$this->model` is returning as bool true, and not an instance. Is this related, or could it be something else that ive done (my code is still as above - didnt want to touch anything else just in case.)

**Comment by goldienz** [comment]
```
public function saveChannelIds($validated_value)
    {
        $selected_channels = $validated_value;
        dd($this->model);
        if (blank($selected_channels)) {
            $this->model->channels()->detach(); //detach all existing relations
        } else {
            $allowed_to_sync = filled($selected_channels) ? array_intersect($selected_channels, array_values($this->channels)) : [];
            if (filled($allowed_to_sync)) $this->model->channels()->sync($selected_channels);
        }
    }
```

**Comment by goldienz** [comment]
Have just been tinkering and it appears that the `$this->model` changes state somewhere in the TallForm.php `success()` function.

Did a dump of `$this->model` before and after this line:
`filled($this->model) && $this->model->exists ? $this->onUpdateModel($model_fields_data) : $this->onCreateModel($model_fields_data);`

Before: return instance of the model as expected
After: returns `true`

Will keep looking as to what is making that change, but hopefully thats helpful.

**Comment by goldienz** [comment]
Please ignore the above 'error'. It was due to lazy copy & paste!

In your example [here](https://github.com/tanthammar/tall-forms/wiki/Create-Form) you have a method that overrides the default `onUpdateModel` function.

```
// Optional method, this already exists in the TallForm trait
    public function onUpdateModel($validated_data)
    {
        $this->model = $this->model->update($validated_data);
    }
```

It CLEARLY states it is optional HAHA

It behaves differently to the `onUpdateModel` function in the TallForm.php file

```
    public function success($model_fields_data)
    {
        // you have to add the methods to your component
        filled($this->model) && $this->model->exists ? $this->onUpdateModel($model_fields_data) : $this->onCreateModel($model_fields_data);

    }
```

The `true` response was coming from the one in my model returning a true to the model being saved, and then setting that as the new value for `$this->model`.

I will close this now as you've solved the initial thing for me, the second part was clearly just a user error!

Thanks!

**Comment by tanthammar** [comment]
@goldienz 
Good catch,
I updated the stubs files and documentation to avoid confusion.
v4.1.4, has the correct syntax in the stub files.

Thank you for telling me.
