### ISSUE TITLE
Can't extend/replace component class

### ISSUE THREAD

**Issue by danielbehrendt** [tanthammar/tall-forms#22]
I'd like to extend/replace the `FieldRoot` class which extends the package FieldRoot class so I've created a custom one under `app/components`. 

In `config/tall-form.php` I've made the following change:

`'field-root' => \App\View\Components\FieldRoot::class,`

but this doesn't seem to be the right way. Can you please show how to get my own class working instead of the package one?

**Comment by tanthammar** [comment]
```php
<?php
//Import the blade component at the top of your config
use App\View\Components\FieldRoot;

//components
        'field-root' => FieldRoot::class,

```
```
php artisan config:clear
```
```
php artisan view:clear
```

**Comment by tanthammar** [comment]
Made a documentation page for this https://github.com/tanthammar/tall-forms/wiki/Vertical-Spacing
