### ISSUE TITLE
$vertical_space how that can change?

### ISSUE THREAD

**Issue by jouniikaheimo** [tanthammar/tall-forms#24]
component default is         
$vertical_space = $this->inArray ? ' py-0 ' : ' py-6 sm:py-5 ';

i'm not found wiki parameters where or how that change... py-6 my project is too mutch ?

**Comment by tanthammar** [comment]
Hi. 
You can alter the settings in the config file, or see Field Styling page or Form Component Styling page, or Field Attributes page, or extend any Blade component. Maybe you are looking to extend the FieldRoot Blade component?

See #22 on how to extend the FieldRoot component and change it to your liking.

**Comment by tanthammar** [comment]
Extend the blade component and override the class() method. You don't have to create a new view if you don't want to.

**Comment by jouniikaheimo** [comment]
Issue solved

**Comment by tanthammar** [comment]
Made a documentation page for this: https://github.com/tanthammar/tall-forms/wiki/Vertical-Spacing
