### ISSUE TITLE
View not found for custom field

### ISSUE THREAD

**Issue by danielbehrendt** [tanthammar/tall-forms#25]
When trying to create a custom field I'm always getting an error that the view could not be found:

`View [fields.checkbox-tree] not found.`

but the view file exists under:

`resources/views/fields/checkbox-tree.blade.php`

The field is used like this:

`App\View\CheckboxTree::make('Categories')->options($categories)`

**Comment by tanthammar** [comment]
Did you solve the other issue about how to replace a blade component?

I don't recognise how you call your component. Need more code to understand what you are doing.

Did you try view:clear and config:clear?

**Comment by danielbehrendt** [comment]
@tanthammar Yes, I've solved the other issue. Thanks for that!

Regarding to this issue, I've got the following code:

In `App\View\CheckboxTree.php`:

```
<?php

namespace App\View;

use Tanthammar\TallForms\BaseField;

class CheckboxTree extends BaseField
{

    public $type = 'checkbox-tree';

    public $options;

    /**
     *
     * @param mixed $value
     * @return CheckboxTree
     */
    public function options($value): self
    {
        $this->options = $value;
        return $this;
    }
}
```

In `App\View\Components\CheckboxTree.php`:

```
<?php

namespace App\View\Components;

use Illuminate\View\View;
use Illuminate\View\Component;
use App\View\CheckboxTree as Field;
use Illuminate\Contracts\Container\BindingResolutionException;
use Tanthammar\TallForms\Traits\Helpers;

class CheckboxTree extends Component
{
    use Helpers;

    public Field $field;
    public string $temp_key;

    /**
     *
     * @param Field $field
     * @param string $tempKey
     * @return void
     */
    public function __construct(Field $field, string $tempKey)
    {
        $this->field = $field;
        $this->temp_key = $tempKey;
    }

    /**
     *
     * @return View
     * @throws BindingResolutionException
     */
    public function render(): View
    {
        return view('tall-forms::components.checkbox-tree');

        // also tried the following

        // return view('components.checkbox-tree');
    }
}
```

In `resources/views/fields/checkbox-tree.blade.php`:

`<x-checkbox-tree :field="$field" :temp-key="$temp_key" />`

In `resources/views/components/checkbox-tree.blade.php`:

```
<div>
    Here we show a category tree
</div>
```

I've also tried view:clear and config:clear

**Comment by tanthammar** [comment]
You have to put the blade view in the folder where this package is looking to find the field view. 
Resources/views/vendor/tall-forms/fields/

**Comment by tanthammar** [comment]
I've updated the docs to be more clear on the file path.
Can you please close your open issues if they are resolved?

**Comment by danielbehrendt** [comment]
> I've updated the docs to be more clear on the file path.

Thanks for that, it works.

> Can you please close your open issues if they are resolved?

Sorry for that, done.
