### ISSUE TITLE
Notify trait custom message with alt message and color and icon

### ISSUE THREAD

**Issue by jouniikaheimo** [tanthammar/tall-forms#26]
example here
<img width="403" alt="image" src="https://user-images.githubusercontent.com/32259223/95012489-a53fe100-0641-11eb-9971-30561dd00b28.png">

so i mean you can select the event message example is  "Successfully saved!" 
and alt message in screenshot example  "Anyone with a link can now view this file." this optional

and screenshot example icon, can change and use example blade-icons and change notify color

i hope you understand what i mean :)

**Comment by tanthammar** [comment]
It is a good idea. Please feel free to make a pull request.

**Comment by jouniikaheimo** [comment]
i do it, early week is so busy but i try make PR  friday or saturday :)

**Comment by tanthammar** [comment]
I will close this issue and we can continue the discussion when you make your PR.
