### ISSUE TITLE
Use translated labels for displaying form errors

### ISSUE THREAD

**Issue by lalov** [tanthammar/tall-forms#27]
Hi, and thanks for a fantastic package!

I'm translating all the labels in the form, so the fields are instantiated using both a label and a key. 
The labels are displayed using the translation. 

The problem is that the form validation messages uses the key, not the translation, to display form errors. 

Is there a way to use the translated labels in the error messages without using the errorMsg() function?

**Comment by tanthammar** [comment]
I don't see the reason to remove the errorMsg() function.
If you wrap your translations with `form_data => [ ]` in your language files all should work as it is.

I created the errorMsg() based on another user request #13, so it might be strange to remove it.

Would like more input from other users on this topic before I decide on the best way to handle this.

(I also created all my language files with the form_data wrapper so I am not very keen on rewriting my apps ;) 

Example
```php
'form_data' => [
                'opening_hours' => 'Opening hours',
                'sponsors' =>
                    [
                        'first_name' => 'First name',
                        'last_name' => 'Last name',
                    ],
               //...
]
```

Or maybe I am misunderstanding you?

 A bit confused with "Is there a way to use the translated labels in the error messages..." How would you want it to work?

**Comment by lalov** [comment]
I think you may have misunderstood what i meant. I do not suggest removing the errorMsg() function. 
What I meant, was that if I define a field with a translated label: 

<pre>
Input::make( $translation, 'shipping_address')->rules('required'), // use $translation for validation messages
</pre>

Then it would be nice if the translation messages would use the $translation instead of looking up a translation for the 'shipping_address' key. If a field is defined using only the name as in you example form then it could continue to work the way it does now. 

<pre>
Input::make('Name')->rules('required'), // look up in translation file
</pre>


However, I see that this is maybe not something you need if you use the translation files as you described... :-) 

I used the Kdion4891\LaravelLivewireForms package before upgrading to Livewire2.
It provies attributes to the validation function:

<pre>
public function submit()
    {
        $this->validate(
            $this->rules(),
            $this->preparedMessages(),
            $this->attributes()
        );
   
   .....
   }


    public function attributes()
    {
        $attributes = [];

        /** @var Field $field */
        foreach ($this->fields() as $field) {

            if ($field->type === 'array') {

                /** @var Field $arrayField */
                foreach ($field->array_fields as $arrayField) {
                    $attributes[$field->key . '.*.' .  $arrayField->name] = $arrayField->placeholder ?? $arrayField->name;
                }

            } else {
                $attributes[$field->key] = $field->label;
            }
        }

        return $attributes;
    }
</pre>

That way, the field->label is used in the validation messages. 

Do you think this is something you want to change?

**Comment by tanthammar** [comment]
That is an interesting idea. Easier than translation files. Could you make a PR?

As long as it's not a breaking change I don't see any reason not to implement it.

**Comment by lalov** [comment]
Great, I will.

**Comment by lalov** [comment]
I created a pull request #28

**Comment by tanthammar** [comment]
@lalov what is the `$this->preparedMessages()`, you have in your example above?

**Comment by lalov** [comment]
`preparedMessages()` is a way to override the validation messages. 

A form component can override the `messages()` function to provide an array of validation messages. 
(I have not used it myself, though)

<pre>
    public function messages()
    {
        return [];
    }

    protected function preparedMessages() {
        $messages = $this->messages();

        foreach ($messages as $key => $message) {
            $messages['form_data.' . $key] = $message;
            unset($messages[$key]);
        }

        return $messages;
    }
</pre>

**Comment by tanthammar** [comment]
I searched for it in the kdion pkg, couldn't find that or the attributes method. Were you using a forked version?

**Comment by lalov** [comment]
Yes, smartcode-ch/laravel-livewire-forms, branch smartcode.

https://github.com/smartcode-ch/laravel-livewire-forms/blob/smartcode/src/FormComponent.php

**Comment by tanthammar** [comment]
Closing this ,as it is implemented in v4.4.1

**Comment by tanthammar** [comment]
@lalov quick note on the `$this->preparedMessages()`:

Thank you for the link to that fork. I see that it is not a method needed for this package as every field has the `errorMsg() `method.

**Comment by lalov** [comment]
I agree :-)
