### ISSUE TITLE
Nested KeyVal fields

### ISSUE THREAD

**Issue by danielbehrendt** [tanthammar/tall-forms#29]
Do you see any chance to support nested KeyVal fields? I'd like to achieve the following:

```
KeyVal::make('Shops')->fields({
    KeyVal::make('Names')->fields([
        Input::make('German', 'de'),
        Input::make('English', 'en'),
    ])
})
```

Should become:

```
<input value="" wire:model.lazy="form_data.shops.2.names.de" name="form_data.shops.2.names.de" type="text">
<input value="" wire:model.lazy="form_data.shops.2.names.en" name="form_data.shops.2.names.en" type="text">
```

**Comment by tanthammar** [comment]
I am sorry to decline your request but I don't see how this would be possible with the current layout loop.

Think it would cause an infinitive loop.

There are also multiple places in validation etc where I am uncertain that this would work without some major refactoring.

I will close this issue for now, but please feel free to make a PR that suits your needs, and I promise to reconsider :)

**Comment by danielbehrendt** [comment]
@tanthammar No problem. Do you have any idea how to collect the input to get the following nested data?

```
{
    "shops": {
        "1": {
            "names": {
                "de": "Foo",
                "en": "Bar
            },
            "descriptions": {
                "de": "Lorem",
                "en": "Ipsum"			
            }            
        }
    }
}
```

**Comment by danielbehrendt** [comment]
> Think it would cause an infinitive loop.

Tried it with a custom `IsArrayField` (which allows arrays and repeater, just for testing) and it didn't cause an infinite loop. But there are problems in building the correct (nested) field names. Validation seems also work as expected.

The "only" problem that I currently see is that the `form_data` in `submit` of `SubmitForm` trait looks like this:

```
array:6 [▼
  "shops.2.active" => null
  "shops.2.names" => null
  "shops.2.descriptions" => null
  "shops.2.long_descriptions" => null
  "shops.2.keywords" => null
  "shops" => array:1 [▼
    2 => array:2 [▼
      "names" => array:1 [▼
        "de" => "Name DE"
      ]
      "descriptions" => array:1 [▼
        "de" => "Description DE"
      ]
    ]
  ]
]
```

but the `$validated_data` looks fine:

```
array:1 [▼
  "shops" => array:1 [▼
    2 => array:2 [▼
      "names" => array:1 [▼
        "de" => "Name DE"
      ]
      "descriptions" => array:1 [▼
        "de" => "Description DE"
      ]
    ]
  ]
]
```

but in `$model_fields_data` the array gets lost.

**Comment by tanthammar** [comment]
@danielbehrendt 

This is the reason I prevent nesting of some field types, I haven't had the time to dig deep on how to make it work.

**_If you resolve the issues I will gladly accept a PR._**

Just pushed this to a later stage because I wanted to release a few more field types before taking on this task.

In v4.4.2 you can override the `$allowed_in_array` on the KeyVal field to play around with it.

**Comment by danielbehrendt** [comment]
I think I've got it so far :)

Currently I'm looking for the position where the field key of the fields in the keyval fields array is modified, because on some point the name get corrected from`form_data.bar` to `form_data.foo.bar` for the following field definition:

```
KeyVal::make('Foo')->fields([
    Input::make('Bar')
]),
```
Do you know where this happens?

**Comment by danielbehrendt** [comment]
@tanthammar I've got it. Will have to do some cleanup and merging and send you a PR when done.
