### ISSUE TITLE
x-spinner.button and SVG icons not working 

### ISSUE THREAD

**Issue by jouniikaheimo** [tanthammar/tall-forms#3]
x-spinner.button and SVG icons not working

**Comment by tanthammar** [comment]
- Please upgrade to 2.03 for the spinner button issue.

Can you explain in what way SVG icons is not working?
- Have you installed and configured laravel-blade-icons package?
- Have you published this package config file and edited the path to your icons?

**Comment by tanthammar** [comment]
I have made an extensive installation tutorial where you can read on how to setup blade icons in your project.
[You can read it here](https://github.com/tanthammar/tall-forms/wiki/Installation-tutorial)
