### ISSUE TITLE
Delete button only & modal confirmation

### ISSUE THREAD

**Issue by goldienz** [tanthammar/tall-forms#30]
Is it possible to hide the save button, and only display the delete button. 

eg:

```
$this->fill([

            'wrapWithView' => false, //see https://github.com/tanthammar/tall-forms/wiki/installation/Wrapper-Layout
            'showGoBack' => false,
            'showReset' => false,
            'showDelete' => true,
            'showSave' => false,
            'inline' => false,
            'showTitle' => false,
        ]);
```

in the `mount()` method in the component.

also, is it possible to have the delete button bring up a modal to confirm a delete action?

**Comment by goldienz** [comment]
I have managed to hack the show delete button only by doing the following:

Tanthammar\TallForms\TallForm

```
    public $model;
    public $form_data;
    public $previous;
    public $showDelete = true;
    public $showReset = true;
    public $showGoBack = true;
    **public $showSave = true;**
    public $custom_data = [];
```
resources/includes/buttons-root.blade.php

```
**@if($showSave)**
            <span x-data="{ open: false }"
                  x-init="@this.on('notify-saved', () => { if (open === false) setTimeout(() => { open = false }, 2500); open = true;})"
                  x-show.transition.out.duration.1000ms="open" style="display: none;"
                  class="text-green-500 pr-4">@svg('solid/check','h-5 w-5') {{ trans(config('tall-forms.saved')) }}</span>
            <x-tall-button type="submit" wire:click.prevent="saveAndStay" wire:loading.attr="disabled" color="positive">
                        <span class="mr-2" wire:loading wire:target="saveAndStay">
                            <x-tall-spinner/></span>
                @lang(config('tall-forms.save-and-stay'))
            </x-tall-button>
**@endif**
```

**Comment by tanthammar** [comment]
Hi @goldienz 

I released 4.4.2 with support for your request to hide the save button.
You can now use the $`showSave` property in your components.

Regarding showing a modal when clicking the delete button;

You have two options, you can publish the buttons-root.blade file and override it or make a PR.

If you make a PR I would want the modal to be optional.
1. global setting in config
2. property on the component

I will close this issue and continue the discussion with you if/when you make a pull request :)
Thank you for your input.

**Comment by goldienz** [comment]
Thanks!

I'll definitely have a think about the modal, or some form of 'confirmation' for deleting records via the delete button.

I completely agree it should be optional, to allow for varying applications.

**Comment by belzaaron** [comment]
Reopen (as in an update on a possible PR, @goldienz?) <3
