### ISSUE TITLE
Problem with "wire:model.lazy"

### ISSUE THREAD

**Issue by danielbehrendt** [tanthammar/tall-forms#34]
I've encountered some problem of the default `wire:model.lazy` of the `HasAttributes` trait in combination with `'onKeyDownEnter' => 'saveAndStay'`.

It seems that when updating values in an input field and hitting enter key (without leaving the input field) the old value gets send. When I change the default to `public $wire = 'wire:model';` everything works fine.

Any chance to make `public $wire` configurable without having to use the wire() method of every field?

**Comment by tanthammar** [comment]
Hi @danielbehrendt 

I tried to reproduce what you are describing, but in a standard text input, I could enter something, hit return (while the field was active), and the value was saved without issues.

However I know that this feature is a bit buggy in Livewire so I moved the default wire:model setting to the config file.

Upgrade to 4.5.0 (Trix field release) and change `config('tall-forms.field-attributes.wire')` setting to your liking.
