### ISSUE TITLE
Does this support multi-step forms?

### ISSUE THREAD

**Issue by crzzano** [tanthammar/tall-forms#38]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
a multi-step form where you can define the fields on each step, sync with a server-side model, and optional ability to traverse form steps as your progress. also would be cool to have support for conditional steps, and before step load or after step load functions (to show a processing/loading animation between steps, or perform some kind of function between steps, for example)

**Describe alternatives you've considered**
you can have a really long form instead 

happy to help develop this, i will give this package a shot now

**Comment by tanthammar** [comment]
Hi @crzzano 
This is the way I would do it.
- I would create a standard Laravel page with the design for the steps.
- Switching steps would be handled by AlpineJS (like tabs, accordion, panels or similar)
- I would create individual tall-form components for each step
    - you can change the submit button text to something like "next step"
    - I would emit an event to the next form on form submit
    - I would utilize lazy loading in all forms except the first step.


This is all possible with the current version.

If you're interested in contributing with a component that does what you describe - it's great!

**Comment by tanthammar** [comment]
@crzzano Is it ok to close this issue?
You are welcome with a PR.

**Comment by tanthammar** [comment]
@crzzano I'm closing this issue, because I'm not getting a reply from you. Look forward to your PR.
