### ISSUE TITLE
Can you make example form readme animation form

### ISSUE THREAD

**Issue by jouniikaheimo** [tanthammar/tall-forms#4]
Animation is feature add new owner... not found the example where that is allready do it.

Thx for that If you cab explain how that do it

**Comment by tanthammar** [comment]
Hello @jouniikaheimo 

I am sorry but I do not understand what you want me to help you with.
You say "Animation is feature add new owner".

Do you mean this?:
```
 Field::make('Owners')->array([
        ArrayField::make('Full Name')->input()->placeholder('Full Name')->rules('required'),
        ArrayField::make('Phone Number')->input('tel')->placeholder('Phone Number'),
    ]),
```

**Comment by jouniikaheimo** [comment]
Yes i mean for dynamic add row... and i mean that gif animations in readme.md  where display how add new row for owners...

now solved problems, btw select field is label is atm bootstrap version :)

**Comment by tanthammar** [comment]
So I can close this issue? You do not need anything else from me :) 
(the form-label class is an option that I you can add to your project. It is documented in the installation tutorial)
