### ISSUE TITLE
'button doesn't show

### ISSUE THREAD

**Issue by santhika29** [tanthammar/tall-forms#41]
**Describe the bug**
I can't get the button show in my form... any clue?

**Screenshots**
![image](https://user-images.githubusercontent.com/3783522/98201357-77b0c500-1f6a-11eb-8e2d-ccd96f077ccd.png)

**Environment:**
 - Tall-forms version: latest
 - Livewire version:latest
 - Laravel version:latest
 - $wrapWithLayout true/false:false
 - Optional model binding?
 - Have you published the view files?: yes
 - Have you published, and edited the config file?: no
 - Is it a Create or Update form?: create

**Fields Definition**
Please paste the code for your fields that is related to this issue.

**Comment by tanthammar** [comment]
@santhika29 Looks like something is wrong with your theme or the colours{} in Tailwind.config. The buttons are visible but not the buttons bg color.
