### ISSUE TITLE
select problem

### ISSUE THREAD

**Issue by santhika29** [tanthammar/tall-forms#43]
**Describe the bug**
'Select' component not show the placeholder when form initiate. the select component show the 1st option not the placeholder, and whe i try to validate, the select shown error message, can you help me figure it out

**Screenshots**
![image](https://user-images.githubusercontent.com/3783522/100043674-e2a63b00-2e48-11eb-9953-83a579a5323a.png)

**Environment:**
 - Tall-forms version: latest
 - Livewire version: latest
 - Laravel version: latest
 - AlpineJS version (only needed if problem is Alpine related):
 - $wrapWithLayout true/false: false
    - if true, Are you using your own wrapper component or the default one?:
 - Optional model binding? yes
 - Have you published the view files?:
 - Have you published, and edited the config file?:
 - Is it a Create or Update form?: create

**Fields Definition**
```
public function fields()
    {
        $optStat = Statuspasien::pluck('id', 'status');
        return [
            Select::make('Status Pasien', 'statuspasien_id')->options($optStat)->placeholder('Please select a Status pasien.'),
            Select::make('Tindakan', 'tindakan_id')->options(Tindakan::pluck('id', 'jenis'))->placeholder('Please select a Tindakan.')->rules('required'),
            Input::make('Harga')->rules(['required','numeric'])->type('number'),
        ];
    }
```

**Comment by santhika29** [comment]
i think it's because disabled tag in select.blade.php 
before : 
`@if($field->placeholder) <option value="" disabled>{{ $field->placeholder }}</option> @endif`
after : 
`@if($field->placeholder) <option value="" >{{ $field->placeholder }}</option> @endif` 

thank u for you awesome package

**Comment by tanthammar** [comment]
Hi @santhika29 
Do you want me to change this to the default behaviour? 
So you don't have to maintain a published view?

**Comment by tanthammar** [comment]
@santhika29 
I fixed this in the latest release. Thank you for reporting.
