### ISSUE TITLE
min, max and step

### ISSUE THREAD

**Issue by santhika29** [tanthammar/tall-forms#44]
**Describe the bug**
i think the min, max and step not working in input field. i already test it in my project.. could u help me to figure it out?

**Screenshots**
![image](https://user-images.githubusercontent.com/3783522/100372891-e2728f00-3044-11eb-872e-d61b12fb0868.png)

**Environment:**
 - Tall-forms version:
 - Livewire version:
 - Laravel version:
 - AlpineJS version (only needed if problem is Alpine related):
 - $wrapWithLayout true/false:
    - if true, Are you using your own wrapper component or the default one?:
 - Optional model binding?
 - Have you published the view files?:
 - Have you published, and edited the config file?:
 - Is it a Create or Update form?:

**Fields Definition**
`
 public function fields()
    {

        return [
            $this->dateLocal(),
            Input::make('Number')
                ->type('number')
                ->prefix('#')
                ->step(2)
                ->min(5)
                ->max(10)
                ->rules('required|integer'),
        ];
    }
    public function dateLocal()
    {
        $today = Carbon::today();
        return Input::make('Tanggal Periksa', 'tgl_periksa')
            ->type('date')
            ->step(7)
            ->min('2020-09-15')
            ->max('2020-11-21') //or now()->format('Y-m-d\TH:i')
            ->rules('required');
    }
`

**Comment by santhika29** [comment]
i think i got the bug...
i already submit a PR then, if you don't mind
in your components/input.php

before:
`
public function options(): array
    {
        ...
        if (in_array($this->field->type, ['number', 'range', 'date', 'datetime-local', 'month', 'time', 'week'])) {
        ..
`

after :
`
public function options(): array
{
        ..
        if (in_array($this->field->input_type, ['number', 'range', 'date', 'datetime-local', 'month', 'time', 'week'])) {
            ..
    `

**Comment by tanthammar** [comment]
Thank you! Merged. See comment in PR.
