### ISSUE TITLE
Support php8

### ISSUE THREAD

**Issue by viezel** [tanthammar/tall-forms#46]
PHP8 has been released and the community is upgrading. 
I did not look into your test suite and source code, but at least we need composer updated. 

composer.json

```json
"require": {
   "php": "^8.0|^7.4",
```

**Comment by tanthammar** [comment]
Hi @viezel 
Can you please try dev-master (where I added 8.0 to composer.json) and confirm that your forms are working without issues.

I couldn't find any errors when I testing.

Would like to use some of the new stuff in php 8 in the package but I will have to wait until Laravel releases a php 8 version.

When I get your confirmation, I'll make a new release.

**Comment by viezel** [comment]
almost all laravel packages have been updated to 8. Im running 3 sites on 8, using the framework. So that's great. 
Only Nova and scout are missing as far as I know.

**Comment by viezel** [comment]
It could help alot of you introduce unit and dusk tests for this package. Then you could setup Github Actions to run on both 7.4 and 8.0 to see if everything is ok. 
Atm, its kind of a shot in the dark with manual testing :D

**Comment by tanthammar** [comment]
I have tests locally. But they are so untidy that I don't wish to share them in public.

Laravel doesn't require 8.0 yet, it's on minimum 7.3.

**Comment by tanthammar** [comment]
Closing. Released v7.0.3

**Comment by viezel** [comment]
https://github.com/laravel/framework/blob/8.x/composer.json#L18

**Comment by viezel** [comment]
cool thanks.

**Comment by tanthammar** [comment]
Yes it says `"php": "^7.3|^8.0"`, Meaning that minimum version is 7.3
When it says `"php": "^8.0"`, I will start upgrading to php8 features. :)
I would really like to use the nullsafe operator.
