### ISSUE TITLE
Add save and new or Reset after save

### ISSUE THREAD

**Issue by haringsrob** [tanthammar/tall-forms#47]
**Is your feature request related to a problem? Please describe.**
When entering a lot of data, it can be useful to quickly add one content after another. Currently, you have to refresh the page or go back and click the create button again.

**Describe the solution you'd like**
We can have 2 solutions (both can work at the same time).

- A button like "Save and add another"
- A property: "ClearOnSave"

**Describe alternatives you've considered**

The following seems to do the trick in `onCreateModel`:

```
            $this->model = Guest::make();
            $this->resetFormData();
            $this->reset('model');
```

**Additional context**
I want to propose a pr, but I want to know if the above is a reasonable solution. Or maybe it already exists and I am missing something.

Thanks for your great package!

**Comment by tanthammar** [comment]
@haringsrob 
Hi, sorry for my late reply.

This is already possible.

You can set the button text with these properties:
```php
    public string $saveStayBtnTxt;
    public string $saveBackBtnTxt;
```
See: https://github.com/tanthammar/tall-forms/wiki/Form-Properties-and-Buttons#string-savestaybtntxt

You can control button visibility:
```php
    public bool $showSave = true;
    public bool $showDelete = true;
    public bool $showReset = true;
    public bool $showGoBack = true;
```
See: https://github.com/tanthammar/tall-forms/wiki/Form-Properties-and-Buttons#string-savestaybtntxt

You can define an action with this method
```php
public function saveAndStayResponse()
    {
        // do your stuff;
        $this->resetFormData();
    }
```
See:  
- https://github.com/tanthammar/tall-forms/wiki/Form-Methods#saveandstayresponse
- https://github.com/tanthammar/tall-forms/wiki/Form-Methods#resetformdata--reset-button
