### ISSUE TITLE
Create form example in Wiki is incorrect

### ISSUE THREAD

**Issue by gavinhewitt** [tanthammar/tall-forms#5]
The example says you should include the component like so:

```
@livewire('user-create-form')
```
but should be (or at least that's what I needed to add):

```
@livewire('forms.user-create-form')
```

**Comment by tanthammar** [comment]
This depends on what `--path` you defined in the artisan `make:tall-form` command.

The default path is `App/Http/Livewire/Forms/`

I updated the docs for better clarity. Thank you for your input.
