### ISSUE TITLE
Repeater Field does not store values using wire:model.defer

### ISSUE THREAD

**Issue by viezel** [tanthammar/tall-forms#57]
**Describe the bug**
When using `Repeater` Form Field combined with `wire:model.defer` only the very last field in the repeater is stored. Please have a look at the screenshots attached.  
I need to use "defer" due to a very large form. 

**Environment:**
 - Tall-forms version: 7.8.0
 - Livewire version: latest
 - Laravel version: latesst
 - AlpineJS version (only needed if problem is Alpine related):
 - $wrapWithLayout true/false: false
 - Optional model binding?
 - Have you published the view files?: no
 - Have you published, and edited the config file?: no
 - Is it a Create or Update form?: both

**Fields Definition**

```php
Input::make('Name')
    ->rules('required')
    ->wire('wire:model.defer'),
          
Repeater::make('Ingredients *', 'ingredients')
    ->fields([
        Input::make('Quantity')->type('number')->rules('required')->colspan(3)->wire('wire:model.defer'),
        Select::make('Unit')->options($unitList)->rules('required|integer')->colspan(3)->wire('wire:model.defer'),
        Select::make('Ingredient')->options($ingredientList)->rules('required|integer')->colspan(6)->wire('wire:model.defer'),
    ])
    ->sortable()
    ->wire('wire:model.defer')
    ->help('Click to add an Ingredient'),

Input::make('Servings')
    ->type('number')
    ->rules('required|integer')
    ->wire('wire:model.defer'),
```

**Screenshots**

If I fill out all fields and hit "save" I get: 

![image](https://user-images.githubusercontent.com/312065/104239875-7fee1a80-545b-11eb-9751-ab99fe5a60df.png)

The below is posted to the backend via Livewire. All the fields and input data are present. 

![image](https://user-images.githubusercontent.com/312065/104240124-de1afd80-545b-11eb-9618-6f3f0d038d92.png)

If I use Selects, Input, Trix etc. outside of a Repeater - then defer works.

**Comment by tanthammar** [comment]
Hi @viezel 
This is something with your project. `->wire()` is ignored on `Repeater`,  `KeyVal`, `Panel` and `Group` fields.

I tested both updatedFoo(), saveFoo() and checked the database after normal submit.

But, I added the `->wire()` methods to these field types, it's available in v7.8.1

Check that you added `$cast` to array on the Model for this field?
It's recommended that your field in db is a json column.

**Comment by viezel** [comment]
alright.. ill keep fighting. Thanks for the update 👍

**Comment by tanthammar** [comment]
@viezel Just a thought. Try removing wire() on all nested fields and apply it only to the `Repater`.

Haven't tested that scenario. 

Please report back if it solved it.
