### ISSUE TITLE
Multiselect TW1 styling

### ISSUE THREAD

**Issue by Zagna** [tanthammar/tall-forms#58]
With Tailwind 1.x and [Tailwind CSS Custom Forms](https://tailwindcss-custom-forms.netlify.app/), multiselect.blade.php select tag is incorrectly styled with form-select when it should be form-multiselect.

![multiselect2](https://user-images.githubusercontent.com/14203328/104933169-3d739300-59b1-11eb-9340-c6c47ce3d1df.png)
Styled with form-select

![multiselect3](https://user-images.githubusercontent.com/14203328/104933197-49f7eb80-59b1-11eb-98aa-938a8429cc15.png)
Styled with form-multiselect

**Environment:**
 - Tall-forms version: 7.8.1

**Comment by tanthammar** [comment]
Thank you for reporting this issue is fixed in the latest release.
