### ISSUE TITLE
Array field not working

### ISSUE THREAD

**Issue by gavinhewitt** [tanthammar/tall-forms#6]
I've used the example in the wiki, but the arrays do not show up. You see only Owner, but other than that there are no other fields. Am I missing something? I believe I've done everything as described.

```
Field::make('Owners')->array([
        ArrayField::make('Full Name')->input()->placeholder('Full Name')->rules('required'),
        ArrayField::make('Phone Number')->input('tel')->placeholder('Phone Number'),
    ]),
```

**Comment by tanthammar** [comment]
Hi @gavinhewitt 
I'll have a look tomorrow. It's 2am in Sweden :) 
At first glance I can't see anything wrong.

**Comment by tanthammar** [comment]
Did you check the layout docs? Are you using SpaMode?
Is it a create or update form?
Which version do you have installed?

Sorry for messy answer. Typing from my phone.

**Comment by gavinhewitt** [comment]
Here in Holland it's 2am too ;-)

Looking forward to your findings!

**Comment by gavinhewitt** [comment]
> Did you check the layout docs? **Yes**
> Are you using SpaMode? **No**
> Is it a create or update form? **Create**
> Which version do you have installed? **The latest**

> Sorry for messy answer. Typing from my phone. **No worries**

**Comment by tanthammar** [comment]
Also, are you using tailwindUI or tailwindcss

**Comment by gavinhewitt** [comment]
> Also, are you using tailwindUI or tailwindcss

Both

**Comment by gavinhewitt** [comment]
Output:

![image](https://user-images.githubusercontent.com/1969103/89476832-00616e80-d78c-11ea-9cb5-bb8dc6b27178.png)

**Comment by tanthammar** [comment]
Can you please post the entire component code here, unable to reproduce your error.

**Comment by tanthammar** [comment]
I think I found the problem. I cannot see any icons in your screenshot. Nor is the button to add an "Owner" visible in the image. Have you installed and setup the laravel-blade-icons package correctly?

You should see a green button with a plus-circle icon below the "Owner" label.

Like this:
![image](https://user-images.githubusercontent.com/21239634/89500614-4cc7a100-d7c2-11ea-80a0-6592e674bed5.png)


When you click on that + button it will look like this:
![image](https://user-images.githubusercontent.com/21239634/89500705-71bc1400-d7c2-11ea-9639-9014630efdb6.png)


Please check the source in the browser. Search for this:
```html
wire:click="arrayAdd('owners')"
```
Is it in the source?
If so, it is the laravel-blade-icon package that is not correctly installed in your projekt. OR you have not published this packages `config` file and defined the icon paths.

**Comment by gavinhewitt** [comment]
Ah yes, I had seen `wire:click="arrayAdd('owners')"` but did not investigate further because somehow I was expecting to see the empty fields by default. This is a clear case of why you should RTFM. :-D

So sorry to keep you busy for nothing!

**Comment by tanthammar** [comment]
If you want to show an empty field set by default you can use the fields default() method. But be aware that it might be annoying to the user if any fields are required or annoying for you to save an empty array to dB...
