### ISSUE TITLE
Input suffix

### ISSUE THREAD

**Issue by dubcanada** [tanthammar/tall-forms#60]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Right now we have prefix to add things before the input field like `$` etc, but it would be nice to have a suffix for things like `.00`.

**Describe alternatives you've considered**
There isn't any without extending the input class, creating a new view and livewire component.

**Additional context**
Nope

**Comment by mertasan** [comment]
#61

**Comment by tanthammar** [comment]
Hello @dubcanada 
Thank you for your suggestion.

I will review the PR from @mertasan to implement your request.

Thank you @mertasan for helping out with this matter :) !!

**Comment by tanthammar** [comment]
Released.

**Comment by dubcanada** [comment]
That was fast, I was meaning to do this myself sometime tomorrow so I'll just pull the latest release. Thanks everyone!
