### ISSUE TITLE
Linking datatable to tall form

### ISSUE THREAD

**Issue by clawes** [tanthammar/tall-forms#66]
Tina,

Could you please provide an example of how to link a datatable to a tall form?
For example, how to connect the update and view actions to a form.

Thanks.

**Comment by tanthammar** [comment]
Add a modal somewhere in your layout. 

Add your form in that modal. Pass an empty Model to the form component. 

Add a dispatch event including a Model with Alpine, on click, of any button. 

Add a listener to your form that updates the Model, shows the model and refreshes the component. 

That's it.
