### ISSUE TITLE
Sponsorship 

### ISSUE THREAD

**Issue by web-schwinge** [tanthammar/tall-forms#67]
Hi Tina,

How can I access the sponsors repository? I signed up as a sponsor a few days ago.

**Comment by tanthammar** [comment]
You should have received an invitation to your GitHub email. 

Please report back if I should resend the invitation.

**Comment by keenminded** [comment]
Hello Tina,

I seem to also be missing the invitation email if it is set up as an automated delivery. If not, could you please resend it at your convenience? Keep up the great work! Thank you for a highly comprehensive forms package.

**Comment by tanthammar** [comment]
@keenminded Thank you for contacting me. Closing, as I answered this on discord :)
