### ISSUE TITLE
Sponsor access

### ISSUE THREAD

**Issue by unixtime** [tanthammar/tall-forms#68]
Hi Tina, 

Thank you for providing this package to the community.

Unfortunately, I Didn't get An invitation Yet since yesterday. Do you mind sending me the 🔗 - Thank you!

**Comment by tanthammar** [comment]
Hi Hassan.
I do everything manually, sorry for the delay. I sent you an invitation to the private repository.
Thank you for your support!
Looking forward to work with you.
