### ISSUE TITLE
$this->model is NULL when you pass a model from Blade directive

### ISSUE THREAD

**Issue by gavinhewitt** [tanthammar/tall-forms#7]
**Describe the bug**
You can't reference the model within the component because it is null.

The reason I'm trying to pass in the model in the directive is that the model instance is also not being picked up from the route. Consider this url:
```
domain.test/admin/term/2569/edit

// Route is declared as
Route::get('/term/{id}/edit', 'TermEdit')
    ->name(term.edit');
```

I'm expecting the fields on the edit form to have data, but they don't. When I dump $term in the component it's empty. I then tried to pass in the model, but that also does not work (tried dumping $this->model).

**Environment:**
 - Tall-forms version: latest
 - Livewire version: latest
 - AlpineJS version (only needed if problem is Alpine related): latest
 - SpaMode true/false: false
    - if true, Are you using your own wrapper component or the default one?:
    - if true, Are you using a Route::livewire for model binding?
 - Have you published the view files?: Yes
 - Have you published, and edited the config file?: Yes
 - Is it a Create or Update form?: Update
 - Have you installed and configured the laravel-blade-icons package?: Yes

**Fields Definition**
Field::make('Title', 'title')->input()->rules('required'),

**Comment by tanthammar** [comment]
Please post your entire form component code :)

**Comment by gavinhewitt** [comment]
```
// TermUpdateForm

namespace App\Http\Livewire\Forms;

use App\Models\Term;
use Tanthammar\TallForms\Field;
use Tanthammar\TallForms\FormComponent;

class TermUpdateForm extends FormComponent
{
    public function mount(Term $term)
    {
        // echo '<pre>';var_dump($term);echo '</pre>';die();
        echo '<pre>';var_dump($this->model);echo '</pre>';die();
        //Gate::authorize()
        $this->fill([
            'formTitle' => 'Term bewerken',
            'action' => 'update',
            'spaMode' => false,
            'showGoBack' => false,
        ]);

        echo '<pre>';print_r($term);echo '</pre>';die();

        $this->mount_form($this->model);
    }

    public function fields()
    {
        return [
            Field::make('Title', 'title')->input()->rules('required'),
        ];
    }
}
```

```
// View

@extends('admin/__base')

@section('content')
    <main class="flex-1 relative z-0 overflow-y-auto focus:outline-none" tabindex="0">
        @livewire('forms.term-update-form', ['model' => $term])
    </main>
@endsection
```

The query is being run I see:

![image](https://user-images.githubusercontent.com/1969103/89528669-b7410700-d7eb-11ea-97bc-d7c7125e7d2d.png)

**Comment by gavinhewitt** [comment]
BTW: there's all these bg-aurora classes being used in the views, but that's not a Tailwind class as far as I know. I know you can change them in the config, but it's a bit odd to have default classes in there that are not part of default Tailwind CSS.

**Comment by tanthammar** [comment]
Hi @gavinhewitt 

There are multiple issues why your form is not working.

You are using route model binding, but you are not passing the model correctly to your component.

You are binding $term to a $model prop
```
@livewire('forms.term-update-form', ['model' => $term])
``` 

But your components mount method does not have a model prop you named it $term.
``mount(Term $term)``

You need to do
``mount(Term $model)``

Then you are not passing the model to the mount_form(), you are trying to pass $this->model which does not exist yet.
``$this->mount_form($this->model);``

You should do this instead
``$this->mount_form($model);``

It looks like you are creating a route only to show the form in  a default layout?

May I suggest that you make a `Route::livewire()` instead and use the spaMode.

That way you can skip the controller and the extra view file and pass the livewire component directly.

Also. You write that you published the view files. I would recommend to hold off on that for a while because I am updating the view files almost daily. The package is just released and I get a lot of input that I want to implement as fast as possible to benefit all users.

If you published the view files it might be hard for you to keep track of bug fixes I make.

**Comment by tanthammar** [comment]
If you use Route::livewire instead the route would look like this

```
Route::livewire('/term/{$term}/edit', 'forms.term-edit')->name(term.edit');
```

No controller or laravel view is necessary. The form will render automatically. Please see the installation tutorial on how to set it up.

Your mount() method would become
```php
    public function mount(Term $term)
    {
        $this->fill([
            'formTitle' => 'Term bewerken',
            'action' => 'update',
            'spaMode' => false,
            'showGoBack' => false,
        ]);

        $this->mount_form($term);
    }
```

I released a new version 2.1 a few minutes ago where I fixed the "aurora" colors.

[After your input I also created an Installation Tutorial in the wiki.](https://github.com/tanthammar/tall-forms/wiki/Installation-tutorial) Please brows through it and give me feedback if it would have solved most of the issues you've had so far.

Your input is valuable, it makes me improve the wiki and solve errors. Thank you.

**Comment by gavinhewitt** [comment]
Awesome @tanthammar! I love how you take action right away. The installation docs are great. Sure helps a lot (I'm a Livewire noob to be honest)

Regarding using Route::livewire: Caleb actually has just announced that he's getting rid of that :-)

**Comment by tanthammar** [comment]
That would be extremely sad. My entire app is built with it. Hope there something better replacing it. 
Where did you read about that?

**Comment by tanthammar** [comment]
By the way, just adding that you do not have to use the prop $model, you can also do:

``` php

//route
Route::get('/term/{term}/edit', 'TermEdit')->name(term.edit');


//laravel blade view
//here, name the prop to term instead of model
@livewire('forms.term-update-form', ['term' => $term])


//livewire component
    public function mount(Term $term)
    {
        // ...

        $this->mount_form($term);
    }

```

It "reads" nicer.

**Comment by tanthammar** [comment]
Got the email about dropping Route::livewire, but Route::get will still work the same so I'm calm now. Just a small refractor. You got me scared there for a while ;)

**Comment by gavinhewitt** [comment]
> Got the email about dropping Route::livewire, but Route::get will still work the same so I'm calm now. Just a small refractor. You got me scared there for a while ;)

Haha yeah, sorry. Hadn't had time to comment yet but it wasn't like he's dropping it entirely. Should have mentioned that ;-)
