### ISSUE TITLE
text field values goes null after set it.

### ISSUE THREAD

**Issue by dhanikwebpatriot** [tanthammar/tall-forms#70]
hi i am using tallforms library for my project, in that i have to get address details from database using postcode.. 
so i am getting that values on postcode(textbox) change event via ajax post request and set those value to other textbox like address, city but after set it within second it becomes null...

can anyone let me know how can i set it? is their any another way in tallforms ?

**Comment by tanthammar** [comment]
Is this the question already discussed in the private discord channel?

**Comment by tanthammar** [comment]
Closing this as I did not hear back from you. Please let me know if I can assist you further.
