### ISSUE TITLE
 php artisan view:cache does not work with version 7.9.3 and above

### ISSUE THREAD

**Issue by nileshd** [tanthammar/tall-forms#72]
**Describe the bug**
I have not been able to cache my views since I upgraded to 7.9.5. Each time it tries to cache views, it breaks on this error
```
   InvalidArgumentException 

  Unable to locate a class or view for component [tall-input-array].
```
When I downgrade to 7.9.2 before the input-array was introduced it works all fine.

**Environment:**
 - Tall-forms version: 7.9.5/7.9.6
 - Livewire version:2.4.4
 - Laravel version:8.40
 - $wrapWithLayout true/false: true
    - if true, Are you using your own wrapper component or the default one?:default
 - Optional model binding?
 - Have you published the view files?:yes
 - Have you published, and edited the config file?:yes
 - Is it a Create or Update form?:no

**Comment by tanthammar** [comment]
Try config:clear before view:cache

**Comment by tanthammar** [comment]
And check that the view is published to the resource view vendor folder.

**Comment by tanthammar** [comment]
Did you create a wrapper view?

**Comment by tanthammar** [comment]
Did you merge the config file?

**Comment by tanthammar** [comment]
@nileshd Is it ok to close this issue?

**Comment by tanthammar** [comment]
@nileshd closing as I didn't hear anything back from you. Please get in touch again if the problem remains.
