### ISSUE TITLE
Add a button inside input

### ISSUE THREAD

**Issue by elfeffe** [tanthammar/tall-forms#75]
I have an input that has a slug, automatically generated from the title.
Sometimes the user wants to change it, but after that, in some cases you need to regenerate it automatically from the title again.
Is it possible to add a button inside the input for that?
Or at least a button below the input.

**Comment by tanthammar** [comment]
Hi @elfeffe 
Every field has multiple slots where you can add a view of your own.
https://github.com/tanthammar/tall-forms/wiki/BaseField-Slots

Feel free to reopen if this is not enough for your issue.
