### ISSUE TITLE
Notifications on a different package?

### ISSUE THREAD

**Issue by elfeffe** [tanthammar/tall-forms#76]
It's just an opinion, I think you should add Notifications to another package, and then require it here.
It will help to spread the word about your packages, there is no "standard" notifications package for Livewire, and not all the people will install the whole tall.-forms package just to get notifications.
Just my opinion.

**Comment by tanthammar** [comment]
Ok, Good idea :) I'll wait for Alpine 3 release first.

**Comment by roni-estein** [comment]
you should call it toasty and have notifications as toasts, and then you can make you icon a slice of toast. 🍞 If you buy the pr0 package you can melt cheese or get a tomato maybe an egg with your toast. I have no idea where I was going with this but thats what I would do

**Comment by tanthammar** [comment]
Laravel Filament has a notification package now. Closing.
