### ISSUE TITLE
How to handle spatie/laravel-translatable fields ?

### ISSUE THREAD

**Issue by invaders-xx** [tanthammar/tall-forms#78]
**Describe the bug**
I use spatie/laravel-translatable package and I am wondering how to handle translatable fields

**Screenshots**

**Environment:**
 - Tall-forms version: latest
 - Livewire version: latest
 - Laravel version: 8
 - AlpineJS version (only needed if problem is Alpine related):
 - $wrapWithLayout true/false: false
    - if true, Are you using your own wrapper component or the default one?:
 - Optional model binding? yes
 - Have you published the view files?: No
 - Have you published, and edited the config file?: published but not modified
 - Is it a Create or Update form?: both

**Fields Definition**
Input::make('Name')->rules('required'),

**Comment by tanthammar** [comment]
I use the KeyVal field for that. 
There is an example for Spatie Translatable on the wiki page for the KeyVal field.
https://github.com/tanthammar/tall-forms/wiki/KeyVal#nested-keyval-example
