### ISSUE TITLE
Hook into form errors

### ISSUE THREAD

**Issue by 1jason1** [tanthammar/tall-forms#81]
Need the ability to hook into form errors so I can call whatever notification I want in javascript to show error to user. 

On long forms, while on mobile, the save button appears to do nothing while an error is displayed above on an element. User doesnt know unless they scroll up. I want to hook into sweetalert2 and let them know with a popup when on Mobile.

**Comment by tanthammar** [comment]
Do you want to dispatch a browser event or do you want a Livewire event hook?

**Comment by tanthammar** [comment]
The easiest way is to add code to your form [Wrapper Layout (link)](https://github.com/tanthammar/tall-forms/wiki/Wrapper-Layout).

```blade
      @if ($errors->any())
           //add some script you like here.
           
          // the errors are loopable
           @foreach ($errors->all() as $error)
                {{ $error }}
            @endforeach
      @endif
```

Please reopen the issue if this answer is sufficient for your needs.

Laravel docs: https://laravel.com/docs/8.x/validation#quick-displaying-the-validation-errors
