### ISSUE TITLE
Disable the "Save" button instead of just showing/hiding it

### ISSUE THREAD

**Issue by 1jason1** [tanthammar/tall-forms#82]
Would like an option to disable the save button instead of just showing/hiding it. 

I've built a hook into the FilePond(PR coming soon) field to not show the save button until the files have completed uploading. Would prefer to disable the save button and show some other text or spinning thing during this process.

**Comment by tanthammar** [comment]
Until you the FilePond PR is complete (Thank you!), please publish and override the `buttons.root.php`
