### ISSUE TITLE
Request is for a "SaveAndShowView" method

### ISSUE THREAD

**Issue by 1jason1** [tanthammar/tall-forms#83]
Feature request is for a "SaveAndShowView" method or similar feature . 

On some forms I dont want the ability for a user to click back which would show the form again. This requires me to put in special tags to detect the user has already submitted the form. If the submitted form completed/submitted successfully then just show a view without the redirect.

**Comment by tanthammar** [comment]
If I understand you correctly;

"If the form component is submitted successfully, render a different blade view, but don't redirect."

That is **not possible, without redirection**, unless you override the [render()](https://github.com/tanthammar/tall-forms/wiki/Form-Methods) method or the [formView()](https://github.com/tanthammar/tall-forms/wiki/Form-Methods) method of the component.

You can however change the Livewire layout property in any of the lifecycle hooks [onCreateModel()](https://github.com/tanthammar/tall-forms/wiki/Lifecycle-Hooks#oncreatemodelvalidated_data) or [onUpdateModel()](https://github.com/tanthammar/tall-forms/wiki/Lifecycle-Hooks#ondeletemodel) 

Example for the onCreateModel hook
```php
public function onCreateModel($validated_data)
{
    $this->model = User::create($validated_data);
    $this->layout = 'layouts/base'; //dynamically change the Livewire layout property
    
}
```

Livewire docs: https://laravel-livewire.com/docs/2.x/rendering-components#custom-layout

It is however **possible with redirection**

Set the buttons
```php
public function mount() {
    $showGoBack = false;
    $saveStayBtnTxt = "Custom save label";
}
``` 

Define where you want to redirect when the form is successfully submitted
```php
    public function saveAndStay()
    {
        $this->submit();  //don't remove this.
        $this->notify(); // if you want to show the success message
        return redirect()->route('foo'); //set the route name where you want to redirect.
    }
```
List with form methods: https://github.com/tanthammar/tall-forms/wiki/Form-Methods
List with properties: https://github.com/tanthammar/tall-forms/wiki/Form-Properties-and-Buttons

Please reopen if you need more help.
