### ISSUE TITLE
How to use it without an associated model?

### ISSUE THREAD

**Issue by elfeffe** [tanthammar/tall-forms#84]
I want to use the forms with https://github.com/livewire-ui/modal

I just need to pass some fields together with their names and values, and I want to handle the "save" by myself.
And I need the form to just render the fields and update the Modal which is a Livewire component. I do what I need from there.
In fact, I don't save it, I just process it outside.

Is it possible to do what I need?

**Comment by tanthammar** [comment]
You will in Tall-forms v8. It will have a "FormInModal" component. v8 will be released next week.

**Comment by invaders-xx** [comment]
Hi,

I am also interested in loading a form in a modal using https://github.com/livewire-ui/modal with a $emit('openModal', 'edit-user') from a livewire datatable ?
Do you have please some inputs how to implement that ?
FYI, I am using version 7.9.9.3 of tall-forms ?
Many thanks in advance

**Comment by tanthammar** [comment]
@invaders-xx It will be available in TALL-forms V8 :)

**Comment by invaders-xx** [comment]
Many thanks for your feedback. Do you have any idea when V8 will be available ?

**Comment by tanthammar** [comment]
I've been waiting for a Livewire entangle issue to be resolved. Looks like it's resolved. 
You can monitor the progress in the v8 branch.

**Comment by invaders-xx** [comment]
Many thanks Tina, I look forward from using V8!
