### ISSUE TITLE
@entangle and conditional show/render

### ISSUE THREAD

**Issue by inmanturbo** [tanthammar/tall-forms#85]
I would like to toggle available content based on a value selected in a select. Is it possible to do this? Typically it would be done using @entangle:

```php
class DummyComponent extends Component
{
    public $showInputs = false;

    public $selectedValue = 'dummy_value_one';

    public function toggleInputs()
    {
        if($this->selectedValue === 'dummy_value_two') {
            $this->showInputs = true;
            return;
         }
         
         $this->showInputs = false;
     }
}

```
```blade
<div x-data="{ open: @entangle('showInputs') }">
    <select wire:change="toggeInputs" wire:model="selectedValue">
         <option value="dummy_value_one" >One</select>
         <option value="dummy_value_two" >Two</select>
    </select>

  {{-- visible only when Two is selected --}}
    <ul x-show="open">
        <li><input type="text"></li>
    </ul>
</div>
```

How might one accomplish this using your wonderful library here? I am not sure this should be a feature request, I have a feeling  from looking at the wiki that something this might already be possible. I'm just not sure how. Perhaps with `wire()` and `inputAttr()`? But then how do I wrap two fields in the same parent div, and how to entange?

**Comment by inmanturbo** [comment]
I was able to solve this by using `inputAttr()` and simply wrapping the component itself in a parent div containing the necessary data attribute.

**Comment by simonbuehler** [comment]
@inmanturbo do you have a minimal sample like showing a input based on a radiobutton being selected??

**Comment by tanthammar** [comment]
@simonbuehler 
https://tina-hammar.gitbook.io/tall-forms/field/conditional-field
combine it with a lifecycle hook
https://tina-hammar.gitbook.io/tall-forms/form/lifecycle-hooks
