### ISSUE TITLE
Use Repeater for HasMany Relationship?

### ISSUE THREAD

**Issue by inmanturbo** [tanthammar/tall-forms#86]
Say you want to create a house, with many bedrooms:

```php
public function fields()
{
    return [
        Input::make('Name')->rules(['required', Rule::unique('houses', 'name')->ignore($this->model->id)]),
        Select::make('Color')->options(['Red', 'Green', 'Blue']),
        Repeater::make('Bedrooms')->fields([
            Input::make('Name')->placeholder('Name')->rules('required'),
            Input::make('Description')->placeholder('Describe ...'),
            Input::make('Square Footage', 'square_ft')->type('number')->required,
        ])->sortable()->help('Click plus to add Bedroom')
        ->relationship(),
    ];
}
```

Creating a new "House" here is pretty straightforward, simply using `saveBedrooms()`. However what about updating the house, and how to make a `Repeater` that loads related "bedrooms"?

**Comment by inmanturbo** [comment]
Currently working around this with (using the House example again):

```php
public function fields()
{
    return [
        Input::make('Name')->rules(['required', Rule::unique('houses', 'name')->ignore($this->model->id)]),
        Select::make('Color')->options(['Red', 'Green', 'Blue']),
        Repeater::make('Bedrooms')->fields([
            Input::make('Name')->placeholder('Name')->rules('required'),
            Input::make('Description')->placeholder('Describe ...'),
            Input::make('Square Footage', 'square_ft')->type('number')->required,
            Input::make('id')->type('hidden')->class('nosy'), // added id here
        ])->sortable()->help('Click plus to add Bedroom')
        ->relationship(),
    ];
}
public function afterFormProperties() {

    foreach($this->model->bedrooms as $index => $model){
        $this->arrayAdd('bedrooms');
        foreach($this->form_data['bedrooms'][$index] as $fieldName => $fieldValue){
            $this->form_data['bedrooms'][$index][$fieldName] = $model->{$fieldName};
        }
    }
}
```

Is there a better way?

**Comment by tanthammar** [comment]
Hi @inmanturbo 

Yes, use `->relation()` or `->custom()` with the `saveFoo()` event hook.

```php
Repeater::make('Bedrooms')->fields([
    //...
])
->sortable()
->help('Click plus to add Bedroom')
->relation()
```

```php
public function saveBedrooms($validated_value)
{
      // Each input value in "bedrooms" are validated at this point
      $bedrooms = $validated_value; //array with validated "bedrooms"

      //but not attached to the model
      $this->model->...
}
```

Documentation: 

* custom: https://github.com/tanthammar/tall-forms/wiki/Custom-Data
* relation: https://github.com/tanthammar/tall-forms/wiki/Relations

**Comment by inmanturbo** [comment]
Hello @tanthammar , thanks for the help.

I'm using the `saveFoo` event hook. What I was asking about was loading the related "bedrooms" , from a relationship I mean rather than a `json` or `array` column, when revisiting the form to  update the resource. 

I suppose aside from my work around above maybe I could just `append` the related `bedrooms` to the house under a different name from the relationship, with an `accessor` something like `getBedroomsArrayAttribute()`, then use `Repeater::make('bedrooms_array')` and `saveBedroomsArray` for the `saveFoo`. 

Or I wonder if they be picked up automatically if I just eager loaded the bedrooms? `HasMany` isn't mentioned in the `Relations` wiki, nor is the `Repeater`. 

Sorry if I'm just being clueless here.

**Comment by tanthammar** [comment]
Ah, sorry. Didn't read properly.
I haven't used it that way.

I'll think it through and get back to you.

**Comment by tanthammar** [comment]
@inmanturbo 

I haven't, and probably wouldn't, do it that way.

My setup with HasMany is to have a separate form for each child. I either hide all the buttons (submit on keydown enter) or keep just the save button.

Something like this.

Parent view 
```blade
{{-- blank form on top to create new items --}}
{{-- clear the form on submit, and emit $refresh to the other forms, for the children to become visible --}}
<livewire:forms.add-bedroom />

{{-- loop hasMany items --}}
@foreach($bedrooms as $bedroom)
  <livewire:forms.bedroom :bedroom="$bedroom"/>
@endforeach
```

You could also have a `div` with a `click` event that hides or shows each child form. Like an "inline edit" thing.
It depends on how many related items you will handle att the same time.

Does this make sense to you?



Or, did you try to map the query toArray?

```php
public function beforeFormProperties() {
    $this->model->temporary_prop = $this->model->bedrooms()->all()->map()->toArray();
}

//fields()
Repeater::make('Bedrooms', 'temporary_prop')->fields([...])->relation();

//saveFoo
public function saveTemporaryProp($validated_data);
{     //I haven't tried this!
       foreach($validated_data as $bedroom) { 
           data_set($bedroom, 'parent_id', $this->model->id);
           $bedroom = Bedroom::firstOrCreate(
                     ['id' => $bedroom['id']],
                     Arr::except($bedroom, ['id']);
            );
       }
}
```

**Comment by tanthammar** [comment]
@inmanturbo 
Please report back if this was an acceptable suggestion, then I'll add it to the docs as an example.

**Comment by inmanturbo** [comment]
Yes that is very helpful. Thank you @tanthammar .
