### ISSUE TITLE
Name attribute in datepicker component

### ISSUE THREAD

**Issue by oliver-yopiter** [tanthammar/tall-forms#88]
Hello,
we noticed that when we create a datepicker component like this:
`Group::make('')->fields([$this->datePickerField('date_of_birth', __('models/persons.fields.date_of_birth'))->colspan(3)])` the created HTML output has no `name` attribute in the input tag like your other components. 
Because we are using some third party scripts to access form inputs by their `name` attribute it would be awesome if you could change the template of the datepicker component so that it is also using the name we provide as first parameter when creating the component (in our case 'date_of_birth').

**Additinal context**
This is how our `FormFields.php` looks like:
`public function datePickerField($name, $name_local)
    {
        return DatePicker::make($name_local, $name)
            ->rules(isset($this->modelClass::$rules[$name]) ? $this->modelClass::$rules[$name] : '');
    }
`

I hope my description is clear to you. If not don't hesitate to ask further questions

**Comment by tanthammar** [comment]
Thank you. I'm working on v8. I'll make sure to add this to the next release.

**Comment by tanthammar** [comment]
@oliver-yopiter I'm working on this topic but unable to find a Flatpickr config option to set the name and id attribute of the generated input.
Any suggestions?

**Comment by oliver-yopiter** [comment]
@tanthammar I'm not sure if it's the right file but in my testings i found that in the file `vendor/tanthammar/tall-forms-sponsors/resources/views/components/date-picker.blade.php` from line 11 to 18 there is the input-tag for the datepicker. There I added the following line `name="{{ $field->name }}"`. So that the input-tag looks like the following:
`<input
                x-ref="dateInput"
                x-model="dateValue"
                value="{{ $value }}"
                type="text"
                name="{{ $field->name }}"
                placeholder="{{ filled($field->placeholder) ? $field->placeholder : trans(config('tall-forms-sponsors.date-picker-placeholder')) }}"
                class="flex-1 w-full outline-none border-none focus:ring-0"
            />`
As said I'm not sure if this is the right place for the change but I got it working with this :)

**Comment by tanthammar** [comment]
Yes that will apply the name attr to the hidden input but not the flatpickr input. 
Is that enough for you?

**Comment by oliver-yopiter** [comment]
Yes, for our purposes this it totally fine

**Comment by tanthammar** [comment]
OK. I've added that to v8.
