### ISSUE TITLE
Disabled Input Feature

### ISSUE THREAD

**Issue by AyoobMH** [tanthammar/tall-forms#89]
**Is your feature request related to a problem? Please describe.**
I have encountered a case where I need to make the input a disabled one, so the user can understand that such an input can't be edited, I have gone through the documentation but couldn't find such a feature. For my use case, it was users that don't have permission to edit a certain input, but still, they can see the input value.

**Describe the solution you'd like**
Include a new function that makes an input disabled, could be something like this
```
Input::make('Email', 'email')
    ->disabled(),
```

**Describe alternatives you've considered**
I couldn't find an alternative for this use case using the forms.

**Additional context**

**Comment by tanthammar** [comment]
Hi @AyoobMH 
You hare correct. There is currently no disabled() method on the fields.
I will add it to v8.
Thank you.
