### ISSUE TITLE
formView possible issue ? 

### ISSUE THREAD

**Issue by jouniikaheimo** [tanthammar/tall-forms#9]
**Environment:**
 - Tall-forms lasted:
 - Livewire lasted:
 - AlpineJS version (only needed if problem is Alpine related): lasted
 - SpaMode false:
   
 - Have you published the view files? yes
 - Have you published, and edited the config file?: yes and no
 - Is it a Create or Update form?: update

edit form not fill fields if use formView, if use only fields and mount functions all works fine...

my code:

```
public function fields()
    {
        return [
            Field::make('first_name')->input()->rules('required')->groupClass('col-span-3'),
            Field::make('last_name')->input()->rules('required')->groupClass('col-span-6'),
            Field::make('calling_name')->input()->rules('required')->groupClass('col-span-6'),
        ];
    }

```

```
public function formView()
    {
        return view('tall-forms::editCustomer', [
            'fields' => $this->fields(),
        ]);
    }
```

fields render fine but no values.

if i remove formView input values works good

**Comment by tanthammar** [comment]
You are overriding the FormComponent `formView()` method and passing a custom view, that means that you loose the functionality of this package and you have to create your own form.

You are also referring to the `tall-forms` namespace when passing your view, there is no editCustomer blade view in this package.

May I ask why you wish to override the formView() method?

**Comment by jouniikaheimo** [comment]
Because i want use multiple layouts forms then i need overwrite formView.. but that issue is solved
