### ISSUE TITLE
FileUpload with spatie/laravel-medialibrary

### ISSUE THREAD

**Issue by pktharindu** [tanthammar/tall-forms#90]
I'm using [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary) to manage all my image files and I'm wondering whether it is possible to get it working with a `FileUpload` field.

Is there a way to achieve this? Couldn't find anything related to this on the docs.

**Comment by tanthammar** [comment]
You can interact with the field value using the standard Livewire hooks as described in the Livewire documentation on file uploads.

**Comment by tanthammar** [comment]
Or you can use the ImageCropper.

**Comment by pktharindu** [comment]
I'll give it a try. Thank you!
