### ISSUE TITLE
Sponsor access?

### ISSUE THREAD

**Issue by elfeffe** [tanthammar/tall-forms#97]
Hi Tina, I'm sponsoring the project, but I didn't get access to the sponsor's repo.
Can you check it, please?

**Comment by craftysyntax** [comment]
Ditto :)

**Comment by tanthammar** [comment]
@elfeffe From what I can see you have access ? 
@craftysyntax I just sent you an invite :)

Thank you for you patience and sponsorship, I invite users manually. Very happy to have you onboard!
Join the private discord channel to get in touch with me more quickly.
