### ISSUE TITLE
Module not found: Error: Can't resolve '@alpinejs/trap'

### ISSUE THREAD

**Issue by luis9430** [tanthammar/tall-forms#98]
hi, i'm installing tall forms, i followed the steps to install it but i have this error 
ERROR in ./resources/js/alpine.js 2:0-34
Module not found: Error: Can't resolve '@alpinejs/trap' in 'C:\laragon\www\tall\resources\js'
and i see in my package.json and @ alpinejs / trap is installed
**Screenshots**
![image](https://user-images.githubusercontent.com/30971535/149552312-18fa7913-d94b-4dc1-bbc5-2d15c565176e.png)

![image](https://user-images.githubusercontent.com/30971535/149553290-a65c355c-91fb-4d23-a677-b2aebaf3a08e.png)

btw everything is updated to the latest version

I hope you can help me, thanks!

**Comment by tanthammar** [comment]
Hi. Yes. 
I just read a tweet from Caleb that Alpine trap is deprecated. Will fix a new release tomorrow. 

Or, not deprecated. It's merged into a new Alpine plugin.

**Comment by tanthammar** [comment]
I released a new version, but it only updates the installation commands stub file.
Alter your app.js accordingly.

https://github.com/tanthammar/tall-forms/releases/tag/8.2.2
